# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=wallet_db

# Stripe Simulator Configuration
stripe.simulator.charges-uri=http://localhost:8080/stripe/charges
stripe.simulator.refunds-uri=http://localhost:8080/stripe/refunds

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.playtomic.tests.wallet=DEBUG 